### ISSUE TITLE
Error when downloading from radio.

### ISSUE THREAD

**Issue by johane73** [egzumer/uvk5-chirp-driver#24]
Hi,
 Great firmware, but I'm having an issue when using Chirp and your driver.

`[2024-01-14 11:41:44,612] chirp.wxui.clone - DEBUG: Using port 'COM7'
[2024-01-14 11:41:44,612] chirp.wxui.clone - DEBUG: Selected <class 'chirp.loaded.uvk5_egzumer.UVK5Radio'>
[2024-01-14 11:41:44,629] chirp.wxui.clone - DEBUG: Showing pre_download prompt
[2024-01-14 11:41:47,211] chirp.wxui.clone - DEBUG: Setting flag for prompt pre_download
[2024-01-14 11:41:47,213] chirp.wxui.clone - DEBUG: Serial opened: Serial<id=0x2412bb1b520, open=True>(port='COM7', baudrate=38400, bytesize=8, parity='N', stopbits=1, timeout=0.25, xonxoff=False, rtscts=False, dsrdtr=False) (rts=True dtr=True)
[2024-01-14 11:41:47,214] chirp.loaded.uvk5_egzumer - DEBUG: Sending hello packet
[2024-01-14 11:41:47,214] chirp.loaded.uvk5_egzumer - DEBUG: Sending command (unobfuscated) len=0x0008:
000: 14 05 04 00 6a 39 57 64   ....j9Wd

[2024-01-14 11:41:47,465] chirp.loaded.uvk5_egzumer - DEBUG: Received reply (unobfuscated) len=0x0014:
000: 18 05 00 00 01 02 02 02   ........
008: 0e 53 50 4a 37 47 ff 01   .SPJ7G..
016: 76 00 c6 00               v.......

[2024-01-14 11:41:47,465] chirp.loaded.uvk5_egzumer - INFO: Found firmware: 
[2024-01-14 11:41:47,629] chirp.wxui.main - WARNING: Failed to backup <chirp.loaded.uvk5_egzumer.UVK5Radio object at 0x000002412BB1B970>: 'bool' object has no attribute 'get_byte_compatible'
Traceback (most recent call last):
  File "chirp\wxui\main.py", line 1496, in _menu_download
  File "chirp\wxui\main.py", line 173, in __init__
  File "C:\Users\Dream\Downloads\uvk5_egzumer.py", line 832, in get_features
    rf.valid_special_chans = self.Get_VFO_CHANNEL_NAMES()
  File "C:\Users\Dream\Downloads\uvk5_egzumer.py", line 777, in Get_VFO_CHANNEL_NAMES
    BANDS = BANDS_STANDARD if not isWide else BANDS_WIDE
  File "chirp\bitwise.py", line 499, in __bool__
  File "chirp\bitwise.py", line 709, in get_value
  File "chirp\bitwise.py", line 219, in get_value
TypeError: 'bool' object is not subscriptable
` 

Any ideas?

**Comment by egzumer** [comment]
This looks like a chirp issue to me. Where did you get the CHIRP program from?
Download newest version and try again.

**Comment by johane73** [comment]
Got latest **chirp next** from Dansplanet (official)

**Comment by egzumer** [comment]
Programming mode is only for firmware upload!
